<?php


/**
 * @file
 * Drupal hooks
 */

/**
 * Implements hook_menu().
 */
function search_api_attachments_menu() {
  $items['admin/config/search/search_api/attachments'] = array(
    'title' => 'Search API attachments',
    'description' => 'Search through file content',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('search_api_attachments_settings_form'),
    'access arguments' => array('administer search_api'),
    'file' => 'search_api_attachments.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

/**
 * Implements hook_search_api_alter_callback_info().
 */
function search_api_attachments_search_api_alter_callback_info() {
  $callbacks['search_api_attachments_alter_settings'] = array(
    'name' => t('File attachments'),
    'description' => t('Search API attachments settings.'),
    'class' => 'SearchApiAttachmentsAlterSettings',
  );
  return $callbacks;
}

/**
 * default excluded file extensions
 */
function search_api_attachments_default_excluded() {
  $default = array('aif', 'art', 'avi', 'bmp', 'gif', 'ico', 'mov', 'oga', 'ogv', 'png', 'psd', 'ra', 'ram', 'rgb');
  return $default;
}
